# Cyberpunk Neon: https://github.com/Roboron3042/Cyberpunk-Neon
# Author: Theo (theo-grivel)
font_family JetBrains Mono
font_size 9.5
font_style bold
cursor_beam_thickness 50
background_opacity 0.8
enable_audio_bell no
confirm_os_window_close 0
allow_remote_control no

#: COLOR SCHEME
foreground #a1e3ff
background #11001a
#background_opacity 0.90
#background_blur 1
background_image none
background_image_layout tiled
#background_image_linear no
#dynamic_background_opacity yes
#background_tint 0.0
#dim_opacity 0.75
#: CYBERPUNK NEON COLOR SCHEME
# Normal colors
color0 #000000
color1 #ff0066
color2 #721fc4
color3 #ffaa00
color4 #00ddff
color5 #ff00ff
color6 #00ffa2
color7 #400085

# Bright colors
color8  #333333
color9  #ff5555
color10 #55ff55
color11 #ffff55
color12 #55ffff
color13 #ff55ff
color14 #55ffff
color15 #ff6eaf

# Extended colors
color16 #ff9900
color17 #ff00aa

#: NEON SELECTION COLOR
selection_foreground #000000
selection_background #00dd60
